version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/local/app/Dockerfile
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./:/usr/src/app
    ports:
      - '1337:1337'
    depends_on:
      - database
    networks:
      - internal

  database:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./docker/local/postgres/data:/var/lib/postgresql/data
    networks:
      - internal


networks:
  internal:
    driver: bridge
